name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main   

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
     
      - name: Run tests
        run: python -m unittest discover -s test
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt || echo "No requirements.txt"

      - name: Build EXE
        run: |
          pyinstaller --onefile main3.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-exe
          path: dist/main3.exe
